### ISSUE TITLE
opam package does not install binary

### ISSUE THREAD

**Issue by vzaliva** [chrisnevers/mkocaml#3]
`opam install mkocaml` works but `mkocaml` is not installed.

**Comment by chrisnevers** [comment]
You might need to run `eval $(opam config env)` to put opam in your PATH, so the binaries you install from it can be run

**Comment by vzaliva** [comment]
I did. I also did `find` in `.opam` directory.

**Comment by vzaliva** [comment]
It is still not updated in OPAM. I beleive you need to add "install" stanza to OPAM file.

**Comment by idkjs** [comment]
I confirm its still not installing the binary on install. Had to build from source then cp.
